spring:
  datasource:
    username: postgres
    password: Gis@2025
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://117.72.46.51:5432/postgres
    hikari:
      #连接的超时时间，默认30000 (毫秒)
      connection-timeout: 5000
      #空闲连接最大存活时间（毫秒）
      idle-timeout: 30000
      #池中连接的最长生命周期，值 0 表示无限生命周期（毫秒）
      max-lifetime: 1800000
      minimum-idle: 10
      maximum-pool-size: 50