spring:
  flyway:
    # 是否启用flyway
    enabled: true
    # 禁用数据库清理
    clean-disabled: true
    # 编码格式，默认UTF-8
    encoding: UTF-8
    # 迁移sql脚本文件存放路径，默认db
    locations: classpath:db/migration
    #  flyway 会在库中创建此名称元数据表，用于记录所有版本演化和状态,同一个库不同项目可能冲突，每个项目一张表来记录
    # TODO 值的后缀指定为当前项目名称
    table: flyway_schema_history_manager
    # 基线版本默认开始序号 默认为 1
    baseline-version: 1
    # 针对非空数据库是否默认调用基线版本,为空的话默认会调用基线版本
    baseline-on-migrate: true
    # 定义 afterMigrateError.sql 要清理的元数据表表名
    placeholders:
      flyway-table: ${spring.flyway.table}
      currentSchema: public
