spring:
  cache:
    type: caffeine
    caffeine:
      spec: maximumSize=1000,expireAfterWrite=5m,recordStats
    redis:
      time-to-live: 30m
      cache-null-values: true
  data:
    redis:
      database: 0
      password: fanlz.999999@blue
      host: 117.72.46.51
      port: 6379
      lettuce:
        pool:
          max-active: 8
          max-idle: 8
          max-wait: -1ms
          min-idle: 0
        shutdown-timeout: 100ms
      redisson:
        config: |
          singleServerConfig:
            address: "redis://${spring.data.redis.host}:${spring.data.redis.port}"
            database: ${spring.data.redis.database}
            idleConnectionTimeout: 10000
            connectTimeout: 10000
            timeout: 3000
            retryAttempts: 3
            retryInterval: 1500
